{% set name = "evotorch" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evotorch-{{ version }}.tar.gz
  sha256: b735bafee14bde189a07fea57c10b61330144bd55572693b31173de9033e6fe7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cma
    - functorch
    - gym
    - matplotlib-base
    - numpy
    - packaging
    - pandas
    - ray-all >=1.0
    - pytorch >=1.10.2

test:
  imports:
    - evotorch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://evotorch.ai
  summary: EvoTorch is an advanced evolutionary computation library built directly on top of PyTorch, created at NNAISENSE.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
