{% set name = "evotorch" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evotorch-{{ version }}.tar.gz
  sha256: 9d711f0615ffb1680aacdabe8846aee4011c681dc55b11e92c04b60a7b548b17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cma
    - functorch
    - gym
    - matplotlib-base
    - numpy
    - packaging
    - pandas
    - ray-all >=1.0
    - pytorch >=1.10.2

test:
  imports:
    - evotorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://evotorch.ai
  summary: EvoTorch is an advanced evolutionary computation library built directly on top of PyTorch, created at NNAISENSE.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
