context:
  name: evotorch
  version: "0.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/evotorch-${{ version }}.tar.gz
  sha256: a3e9fd7acf1a7506c763ab5baa78f1dd27f4b212d43da3158d1b9a42c7e374b9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - cma
    - gym
    - matplotlib-base
    - numpy
    - packaging
    - pandas
    - ray-all >=1.0
    - pytorch >=1.10.2

tests:
  - python:
      imports:
        - evotorch
      python_version: ${{ python_min }}.*

about:
  summary: EvoTorch is an advanced evolutionary computation library built directly on top of PyTorch, created at NNAISENSE.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://evotorch.ai

extra:
  recipe-maintainers:
    - hadim
